#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Usage: ARCH=arm64 VERSION=v1.2.3 ./build.sh
#
# ARCH defaults to the host architecture and VERSION to "dev", so a bare
# ./build.sh still just builds a local binary. The release workflow sets both.

ARCH="${ARCH:-$(uname -m)}"
VERSION="${VERSION:-dev}"
VERSION_CLEAN="${VERSION#v}"

mkdir -p build/gen

# The version is compiled in through a generated file rather than patched into
# a source file in place, so a release build never leaves the tree dirty.
cat > build/gen/Version.swift <<EOF
// Generated by build.sh — do not edit.
let kullerVersion = "$VERSION_CLEAN"
EOF

swiftc \
  -O \
  -whole-module-optimization \
  -target "${ARCH}-apple-macos14.0" \
  Sources/*.swift \
  build/gen/Version.swift \
  -o "build/kuller-${ARCH}"

# Stable path for local use, whatever the host architecture is.
ln -sf "kuller-${ARCH}" build/kuller

echo "Built build/kuller-${ARCH} (version ${VERSION_CLEAN})"
